version: "0"
name: do-tabs
services:
  frontend:
    image: vainilla-ts/dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: do-tabs
    volumes:
      - .:/app
      - ./src:/app
      - ./public:/app
      - ./node_modules:/app
    ports:
      - 5900:5173
